stages:
 - update

update-job:
  stage: update
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - cd ..
    - ls -l
    - git clone https://gitlab-ci-token:$ACCESS@git.coagulate.net/CoagulateSL/LSLR.git
    - cd LSLR
    - git submodule init
    - git submodule update --remote --recursive
    - git config --global user.name 'GitLab bot'
    - git config --global user.email 'gitlabbot@predestined.net'
    - git commit -am "Updated SLCore" && git push || echo "No changes to commit"
    - cd ..
    - git clone https://gitlab-ci-token:$ACCESS@git.coagulate.net/CoagulateSL/Billing.git
    - cd Billing
    - git submodule init
    - git submodule update --remote --recursive
    - git config --global user.name 'GitLab bot'
    - git config --global user.email 'gitlabbot@predestined.net'
    - git commit -am "Updated SLCore" && git push || echo "No changes to commit"    
