name: Compile Test

on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      
    steps:
      - name: Checkout SLCore
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/SLCore'
          path: SLCore     
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'        
      - name: Build with Maven
        env: 
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
        working-directory: SLCore
        run: mvn clean compile
        
