name: Release

on:
  push:
    branches:
      - master
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      
    steps:
      - name: Checkout depender GPHUD
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/GPHUD'        
          path: GPHUD
          token: ${{ secrets.PACKAGE_READ }}
          submodules: true
      - name: Git Submodule Update
        working-directory: GPHUD
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit update
        working-directory: GPHUD
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CoagulateSL/GPHUD
          git commit -am "Updated SLCore" && git push || echo "No changes to commit"
      - name: Checkout depender LSLR
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/LSLR'        
          path: LSLR
          token: ${{ secrets.PACKAGE_READ }}
          submodules: true
      - name: Git Submodule Update
        working-directory: LSLR
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit update
        working-directory: LSLR
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CoagulateSL/LSLR
          git commit -am "Updated SLCore" && git push || echo "No changes to commit"
        
